# Generated by Django 5.2.14 on 2026-05-16 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Sizning shaxsiy havola nomingiz (masalan: alimov)', unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='profile_logos/')),
                ('title', models.CharField(help_text='Sahifa sarlavhasi (Brand nomi)', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Qisqacha tavsif matni', null=True)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='backgrounds/')),
                ('theme_color', models.CharField(default='rgba(143, 113, 56, 0.65)', max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
