# Generated by Django 5.2.14 on 2026-05-16 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Tugma matni', max_length=100)),
                ('subtitle', models.CharField(blank=True, help_text='Ostki matn', max_length=150, null=True)),
                ('url', models.URLField(help_text="O'tish havolasi")),
                ('icon_type', models.CharField(choices=[('phone', 'Call Center'), ('telegram', 'Telegram'), ('youtube', 'YouTube'), ('instagram', 'Instagram'), ('globe', 'Veb-sayt')], default='globe', max_length=20)),
                ('order', models.PositiveIntegerField(default=0, help_text='Tartib raqami')),
                ('is_active', models.BooleanField(default=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='profiles.profile')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
