# Generated by Django 5.2.14 on 2026-05-17 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='icon_type',
            field=models.CharField(choices=[('phone', 'Telefon'), ('telegram', 'Telegram'), ('instagram', 'Instagram'), ('youtube', 'YouTube'), ('pubg', 'PUBG Mobile ID'), ('mlbb', 'Mobile Legends'), ('beelink', 'Beelink'), ('globe', 'Boshqa sayt')], default='globe', max_length=20),
        ),
        migrations.AlterField(
            model_name='link',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='link',
            name='subtitle',
            field=models.CharField(blank=True, help_text="Masalan: Nickname yoki o'yin ID raqami", max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.URLField(blank=True, help_text="O'yin tugmalari uchun bo'sh qoldirsa ham bo'ladi", null=True),
        ),
    ]
