# Generated by Django 5.2.14 on 2026-05-17 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_alter_link_icon_type_alter_link_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='action_type',
            field=models.CharField(choices=[('link', "Havolaga o'tish (Link)"), ('copy', 'Matnni nusxalash (Copy)')], default='link', help_text='Tugma bosilgandagi harakat turi', max_length=10),
        ),
        migrations.AlterField(
            model_name='link',
            name='subtitle',
            field=models.CharField(blank=True, help_text='Nusxalanadigan ID yoki kichik matn', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.URLField(blank=True, help_text="Havolaga o'tish rejimi uchun URL manzil", null=True),
        ),
    ]
