# Generated by Django 5.2.14 on 2026-05-18 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0003_link_action_type_alter_link_subtitle_alter_link_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='action_type',
            field=models.CharField(choices=[('link', "Havolaga o'tish (Link)"), ('copy', 'Matnni nusxalash (Copy)')], default='link', max_length=10, verbose_name='Tugma rejasi (Harakat turi)'),
        ),
        migrations.AlterField(
            model_name='link',
            name='icon_type',
            field=models.CharField(choices=[('phone', 'Telefon'), ('telegram', 'Telegram'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('linkedin', 'LinkedIn'), ('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('twitter', 'Twitter / X'), ('github', 'GitHub'), ('pubg', 'PUBG Mobile ID'), ('mlbb', 'Mobile Legends ID'), ('freefire', 'Free Fire ID'), ('spotify', 'Spotify'), ('apple_music', 'Apple Music'), ('app_store', 'App Store'), ('play_market', 'Google Play Market'), ('beelink', 'Beelink'), ('globe', 'Boshqa veb-sayt havolasi')], default='globe', max_length=20, verbose_name='Belgi (Icon)'),
        ),
        migrations.AlterField(
            model_name='link',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Aktivmi'),
        ),
        migrations.AlterField(
            model_name='link',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Tartibi'),
        ),
        migrations.AlterField(
            model_name='link',
            name='subtitle',
            field=models.CharField(blank=True, help_text="Tugma ostida kichik harflar bilan ko'rinadigan yozuv", max_length=150, null=True, verbose_name='Kichik matn (Ixtiyoriy)'),
        ),
        migrations.AlterField(
            model_name='link',
            name='title',
            field=models.CharField(help_text="Masalan: Men bilan bog'lanish yoki PUBG ID raqamim", max_length=100, verbose_name='Tugma nomi'),
        ),
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.CharField(blank=True, help_text="Reja 'Link' bo'lsa sayt manzilini (http://...), 'Copy' bo'lsa nusxalanadigan ID yoki matnni yozing.", max_length=500, null=True, verbose_name='Havola (Link) yoki Nusxa olinadigan ID'),
        ),
    ]
